apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  creationTimestamp: null
  labels:
    # io.kompose.service: front
  name: front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: front
  template:
    metadata:
      labels:
        app: front
      annotations:
        kompose.cmd: kompose convert -f docker-compose.yml
        kompose.version: 1.20.0 (f3d54d784)
      # creationTimestamp: null
      # labels:
      #   io.kompose.network/myapp: "true"
      #   io.kompose.service: front
    spec:
      containers:
      - image: alontrubin13/quotes-front:v4
        name: front
        ports:
        - containerPort: 5000
        resources: {}
      restartPolicy: Always
status: {}
