apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.yml
    kompose.version: 1.20.0 (f3d54d784)
  labels:
    app: data-script
  name: data-script
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-script
  template:
    metadata:
      labels:
        app: data-script
    spec:
      containers:
      - image: alontrubin13/quotes-datascript:v3
        name: data-script
        env:
        - name: MYSQL_DB_HOST
          valueFrom:
            secretKeyRef:
              name: datascript-secret
              key: MYSQL_DB_HOST
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: datascript-secret
              key: MYSQL_USER
        - name: MYSQL_USER_PASSWORD
          valueFrom:
            secretKeyRef:
              name: datascript-secret
              key: MYSQL_USER_PASSWORD
      initContainers:
      - name: wait-for-db
        image: mysql:5.7  # Use the same MySQL image
        command: ['sh', '-c', "until mysql -h ${MYSQL_DB_HOST} -u ${MYSQL_USER} -p${MYSQL_USER_PASSWORD} -e 'show databases;'; do echo waiting for mydb; sleep 2; done"]
        env:
          - name: MYSQL_DB_HOST
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: MYSQL_DB_HOST
          - name: MYSQL_USER
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: MYSQL_USER
          - name: MYSQL_USER_PASSWORD
            valueFrom:
              secretKeyRef:
                name: datascript-secret
                key: MYSQL_USER_PASSWORD
  strategy: {}
